name = "SwissVAMyKnife"
uuid = "fafdf525-54c7-48ec-ae29-528bd4cccfab"
authors = ["roflmaostc <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
DiffImageRotation = "cb1f95eb-7c3a-45bc-9e18-5c07f1beaacd"
RadonKA = "86de8297-835b-47df-b249-c04e8db91db5"
WaveOpticsPropagation = "c4c7a1f9-3adc-4a73-843a-d378b6c86436"
